In [1]:
from absenteeism_module import *

In [2]:
pd.read_csv('Absenteeism_new_data.csv')

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

In [3]:
model = absenteeism_model('model.pkl','scaler.pkl')

In [4]:
model.load_and_clean_data('Absenteeism_new_data.csv')

In [5]:
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,False,0.0,False,True,6,4,179,26,30,237.656,19,1,0,0,0.118840,0
1,True,0.0,False,False,6,0,361,52,28,237.656,27,0,1,4,0.902884,1
2,False,0.0,False,True,6,2,155,12,34,237.656,25,0,2,0,0.315454,0
3,False,0.0,False,True,6,4,179,22,40,237.656,22,1,2,0,0.187436,0
4,True,0.0,False,False,6,4,155,12,34,237.656,25,0,2,0,0.720326,1
5,True,0.0,False,False,6,0,225,26,28,237.656,24,0,1,2,0.786948,1
6,True,0.0,False,False,6,2,118,15,46,275.089,25,0,2,0,0.566361,1
7,False,0.0,False,True,6,2,179,26,30,275.089,19,1,0,0,0.140765,0
8,False,0.0,False,True,6,4,118,10,37,275.089,28,0,0,0,0.111271,0
9,True,0.0,False,False,6,2,118,10,37,275.089,28,0,0,0,0.517660,1
10,False,0.0,False,True,6,3,378,49,36,275.089,21,0,2,4,0.461620,0
11,False,0.0,True,False,6,3,118,13,50,275.089,31,0,1,0,0.529747,1
12,False,0.0,True,False,6,4,233,51,31,275.089,21,1,1,8,0.235393,0
13,False,0.0,False,True,6,4,179,26,30,275.089,19,1,0,0,0.116831,0
14,False,0.0,False,False,6,0,235,29,48,275.089,33,0,1,5,0.066285,0
15,False,0.0,False,False,6,3,268,11,33,275.089,25,1,0,0,0.151366,0
16,False,0.0,True,False,6,3,118,13,50,275.089,31,0,1,0,0.529747,1
17,True,0.0,False,False,6,3,179,26,30,275.089,19,1,0,0,0.504696,1
18,False,0.0,False,True,6,3,291,31,40,275.089,25,0,1,1,0.383239,0
19,True,0.0,False,False,7,0,179,26,30,275.089,19,1,0,0,0.589598,1
20,False,0.0,False,True,7,0,118,10,37,275.089,28,0,0,0,0.164189,0
21,False,0.0,False,True,7,3,233,51,31,275.089,21,1,1,8,0.042033,0
22,True,0.0,False,False,7,4,118,10,37,275.089,28,0,0,0,0.469937,0
23,True,0.0,False,False,7,2,118,10,37,275.089,28,0,0,0,0.523342,1
24,False,0.0,False,True,7,2,233,51,31,275.089,21,1,1,8,0.046555,0
25,False,0.0,False,True,7,2,235,20,43,264.604,38,0,1,0,0.506861,1
26,False,0.0,True,False,7,4,233,51,31,264.604,21,1,1,8,0.240504,0
27,True,0.0,False,False,7,0,228,14,58,264.604,22,0,2,1,0.669752,1
28,False,0.0,False,True,7,0,118,10,37,264.604,28,0,0,0,0.164933,0
29,True,0.0,False,False,7,1,228,14,58,264.604,22,0,2,1,0.645690,1
30,False,0.0,False,True,7,1,189,29,33,264.604,25,0,2,2,0.294769,0
31,False,0.0,False,True,7,2,118,10,37,264.604,28,0,0,0,0.137548,0
32,False,0.0,False,True,7,2,361,52,28,264.604,27,0,1,4,0.522497,1
33,False,0.0,False,True,7,2,225,26,28,264.604,24,0,1,2,0.303008,0
34,True,0.0,False,False,7,0,369,17,31,264.604,25,0,3,0,0.982701,1
35,True,0.0,False,False,7,1,289,36,33,264.604,30,0,2,1,0.931449,1
36,True,0.0,False,False,7,1,235,11,37,264.604,29,1,1,1,0.784408,1
37,False,0.0,False,False,7,1,118,14,40,271.219,34,0,1,8,0.013636,0
38,False,0.0,False,False,7,2,231,35,39,271.219,35,0,2,2,0.224335,0
39,False,0.0,False,False,7,4,179,45,53,271.219,25,0,1,1,0.036455,0